Visitor can navigate to 'How This Works' and 'Contact' views
CraftAcademy/being_stockholm-client pull request #25
Opened 2019-06-23 16:42 UTC by leiter007

# [PT Story](https://www.pivotaltracker.com/story/show/166861570)

### Changes proposed in this PR
* Content and styling for the `How this works` component, containing instructions on how to use the app, including mock screenshots to be replaced later
* Adds route for `How this works` component in app.js
* Content and styling for the `Contact` component, containing contact info to BeingStockholm - provided by Yat
 
### What we have learned
* More on Semantic UI and site overrides

### Screenshots
<img width="359" alt="Screenshot 2019-06-23 at 18 41 07" src="https://user-images.githubusercontent.com/48205436/59979316-83eee900-95e6-11e9-9418-a26b47e79025.png">
<img width="359" alt="Screenshot 2019-06-23 at 18 40 48" src="https://user-images.githubusercontent.com/48205436/59979319-8b15f700-95e6-11e9-9d0e-9a6f4ce5dc73.png">
<img width="358" alt="Screenshot 2019-06-23 at 18 41 00" src="https://user-images.githubusercontent.com/48205436/59979322-8ea97e00-95e6-11e9-8c85-ba73a5879c04.png">

2019-06-23 17:12 UTC, raptorf1 requested changes

2019-06-23 17:12 UTC, raptorf1 commented on src/Components/Contact.jsx
> +            </Container>
delete empty lines

2019-06-23 18:40 UTC, zanenkn commented
Id use some icons on the get in touch page instead of E, T and A. (yes, this is the graphic designer talking here lol. Also ETA makes me think of "estimated time of arrival" which is totally irrelevant here.)
http://www.zondicons.com/icons.html

2019-06-23 18:45 UTC, zanenkn requested changes

2019-06-23 18:45 UTC, zanenkn commented on src/Components/Contact.jsx
> +              </p>
code formatting

2019-06-23 18:45 UTC, zanenkn commented on src/Components/HowThisWorks.jsx
> +            </Header>
code formatting

2019-06-23 18:45 UTC, zanenkn commented on src/Components/HowThisWorks.jsx
> +              </p>
code formatting

2019-06-24 08:19 UTC, raptorf1 commented on src/Components/Contact.jsx
> +              </p>
done

2019-06-24 08:20 UTC, raptorf1 commented on src/Components/HowThisWorks.jsx
> +              </p>
done

2019-06-24 08:20 UTC, raptorf1 commented on src/Components/HowThisWorks.jsx
> +            </Header>
done

2019-06-24 08:45 UTC, raptorf1 commented
> Id use some icons on the get in touch page instead of E, T and A. (yes, this is the graphic designer talking here lol. Also ETA makes me think of "estimated time of arrival" which is totally irrelevant here.)
> http://www.zondicons.com/icons.html

Done ;)

2019-06-24 08:46 UTC, zanenkn approved these changes

2019-06-24 08:46 UTC, merged