Visitor can see and navigate via footer
CraftAcademy/being_stockholm-client pull request #9
Opened 2019-06-14 13:48 UTC by leiter007

# [PT Story](https://www.pivotaltracker.com/story/show/166572746)

## Changes proposed in this pull request:
* Integration test for seeing headline in footer, and showing menu sidebar
* Adds component MenuSidebar, showing when clicked on hamburger menu icon in Footer
* Adds global site variable for color "orange" to be able to adjust CSS fontcolor across the App
* Removes MainContent component and puts Map in App.js to access props across the app  

## What I have learned working on this feature:
* Creating sidebar in Semantic UI
* Responsiveness of different screen sizes
* Using Semantic UI site variables for color

## Screenshot:
<img width="385" alt="Screenshot 2019-06-14 at 15 46 38" src="https://user-images.githubusercontent.com/48205436/59513748-c82e0b00-8ebb-11e9-9972-5a74ade83312.png">
<img width="430" alt="Screenshot 2019-06-14 at 15 46 55" src="https://user-images.githubusercontent.com/48205436/59513757-cb28fb80-8ebb-11e9-9432-a119bcb6b7a9.png">

2019-06-14 13:59 UTC, zanenkn commented
it is a beautiful thing you guys have made!!!!

Although. I pulled it down and tested in different formats. noticed those borders at the footer, imo unnecessary and in certain formats look weird, for example:

2019-06-14 13:59 UTC, zanenkn commented
![image](https://user-images.githubusercontent.com/48257682/59514572-68d0fa80-8ebd-11e9-94f8-49cddc89a694.png)

2019-06-14 14:00 UTC, zanenkn commented
I suggest we take those away (sorry Felix, i know you love your dividers)

2019-06-14 14:17 UTC, leiter007 commented
> I suggest we take those away (sorry Felix, i know you love your dividers)

I know, a bit strange - trying to find where this is set. Because it is actually NOT any of my lovely dividers.. :)

2019-06-14 14:23 UTC, zanenkn commented
i figured, dividers are ugly but at least you place them evenly, this didnt look like your doing..

2019-06-14 20:57 UTC, raptorf1 requested changes

2019-06-14 20:57 UTC, raptorf1 commented on src/Components/Footer.jsx
> +
`Container` is not used in this component

2019-06-15 11:47 UTC, raptorf1 commented on src/Components/Footer.jsx
> +
removed

2019-06-15 11:48 UTC, merged